[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@anthropic-ai/sdk"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/hvac_jack"
  to = "/HVAC_Jack.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/HVAC_Jack.html"
  status = 200

[dev]
  functions = "netlify/functions"

[template.environment]
  CLAUDE_API_KEY = "Your Claude API key from Anthropic"
  ANTHROPIC_API_KEY = "Your Anthropic API key (fallback)"
