[build]
  base = "."
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@anthropic-ai/sdk"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/HVAC_Jack_Mobile_Updated.html"
  status = 200
  force = true

[dev]
  functions = "netlify/functions"
  publish = "."
