[build]
  base = "apps/hvac-jack/HVAC_Jack_temp"
  publish = "."
  command = "echo 'HVAC Jack 4.0 build'"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"